# FROM python:3
# ENV PYTHONUNBUFFERED=1
# WORKDIR /web/
# COPY docker/requirements.txt /web/
# RUN pip install -r requirements.txt
# COPY . /web/

# Base build
FROM python:3.10-alpine as base
RUN apk add --update --virtual .build-deps \
    build-base \
    postgresql-dev \
    python3-dev \
    libpq

WORKDIR /web/
COPY docker/requirements.txt /web/
# RUN apt-get -y install python3-pip libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0 libffi-dev libjpeg-dev libopenjp2-7-dev
# RUN apk add python3-pip python3-cffi python3-brotli libpango-1.0-0 libpangoft2-1.0-0
# py3-pip gcc musl-dev python3-dev pango zlib-dev jpeg-dev openjpeg-dev g++ libffi-dev
RUN pip install -r requirements.txt
RUN pip install psycopg2-binary --no-binary psycopg2-binary     

# Now multistage build
FROM python:3.10-alpine
WORKDIR /web/
RUN apk add libpq
RUN apk add --no-cache bash
RUN apk add py3-pip py3-pillow py3-cffi py3-brotli gcc musl-dev python3-dev pango
COPY --from=base /usr/local/lib/python3.10/site-packages/ /usr/local/lib/python3.10/site-packages/
COPY --from=base /usr/local/bin/ /usr/local/bin/
COPY . /web/
ENV PYTHONUNBUFFERED 1