
events {}

http {

    include mime.types;

    map $http_x_forwarded_proto $forwarded_proto {
        default $http_x_forwarded_proto;
        '' $scheme;
    }

    upstream app_server {
      # fail_timeout=0 means we always retry an upstream even if it failed
      # to return a good HTTP response (in case the Unicorn master nukes a
      # single worker for timing out).

      server web:8000;
    }
    # server {
    #     listen 80;
    #     server_name dss.ihes.mx;
    #     if ($host = 147.182.201.179) {
    #         return 301 https://dss.ihes.mx/$request_uri;
    #     } 
    #     location / {
    #         return 301 https://$host$request_uri;
    #     }
    #     location /.well-known/acme-challenge/ {
    #         root /var/www/certbot;
    #     }
    # }
    server {
        server_name _;
        listen 8080;#443 ssl;
        client_max_body_size 10M;
        charset utf-8;

        # ssl_certificate /etc/letsencrypt/live/dss.ihes.mx/fullchain.pem;
        # ssl_certificate_key /etc/letsencrypt/live/dss.ihes.mx/privkey.pem;
        # include /etc/letsencrypt/options-ssl-nginx.conf;
        # ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        # access_log /web/docker/nginx-access.log;
        # error_log /web/docker/nginx-error.log;        

        location /static/ {
            autoindex on;
            alias /static/;
        }
        # for medi<p></p>a and static files
        location /media/ {
            autoindex on;
            alias /web/media/;
        }        

        location = /favicon.ico { access_log off; log_not_found off; }
          
        location / {
            proxy_pass http://app_server;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto $forwarded_proto;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_redirect off;
            #proxy_set_header X-Real-IP $remote_addr;
        }

        # Error pages
        error_page 404 /404.html;
        location = /404.html {
            alias /web/app/api/templates/404.html;
            internal;
        }

        error_page 500 502 503 504 /500.html;
        location = /500.html {
            alias /web/app/api/templates/500.html;
            internal;
        }
    }
}
#curl localhost:8000/static/500.html
#curl localhost:8000/media/test.txt
