# Generated by Django 3.0 on 2022-05-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre In-game')),
                ('discord', models.CharField(max_length=50, verbose_name='Nombre discord')),
                ('ilvl', models.PositiveIntegerField(verbose_name='Item Level')),
                ('schedule', models.IntegerField(choices=[(0, '00:00 ST'), (1, '01:00 ST'), (2, '02:00 ST'), (3, '03:00 ST'), (4, '04:00 ST'), (5, '05:00 ST'), (6, '06:00 ST'), (7, '07:00 ST'), (8, '08:00 ST'), (9, '09:00 ST'), (10, '10:00 ST'), (11, '11:00 ST'), (12, '12:00 ST'), (13, '13:00 ST'), (14, '14:00 ST'), (15, '15:00 ST'), (16, '16:00 ST'), (17, '17:00 ST'), (18, '18:00 ST'), (19, '19:00 ST'), (20, '20:00 ST'), (21, '21:00 ST'), (22, '22:00 ST'), (23, '23:00 ST')], verbose_name='Horario')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_class', models.IntegerField(choices=[(0, 'Warrior'), (1, 'Gunner'), (2, 'Mage'), (3, 'Fighter'), (4, 'Assasin'), (5, 'Artist')], verbose_name='Main class')),
                ('sub_class', models.IntegerField(choices=[(0, 'Berserker'), (1, 'Gunlancer'), (2, 'Destroyer'), (3, 'Holly knight'), (4, 'Deadeye'), (5, 'Blaster'), (6, 'Sharpshooter'), (7, 'Scouter'), (8, 'Gunslinger'), (9, 'Summoner'), (10, 'Bard'), (11, 'Sorceress'), (12, 'Arcana'), (13, 'Scrapper'), (14, 'Soulfist'), (15, 'Wardancer'), (16, 'Lance Master'), (17, 'Striker'), (18, 'Demonic'), (19, 'Deathblade'), (20, 'Reaper'), (21, 'Artist')], verbose_name='Sub class')),
                ('class_type', models.IntegerField(choices=[(0, 'DPS'), (1, 'Support')], verbose_name='Class Type')),
            ],
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('stage', models.IntegerField(choices=[(0, 'North Vern'), (1, 'Rohendel'), (2, 'Yorn'), (3, 'Alaric'), (4, 'Oreha Normal'), (5, 'Oreha Hard'), (6, 'Argos P1'), (7, 'Argos P2'), (8, 'Argos P3'), (9, 'Valtan Normal'), (10, 'Valtan Hard')], verbose_name='Stage')),
                ('date', models.DateTimeField(verbose_name='Fecha y hora')),
                ('min_ilvl', models.PositiveIntegerField(default=340, verbose_name='Item Level minimo')),
                ('player_num', models.PositiveIntegerField(default=4, verbose_name='Players per party')),
                ('notes', models.TextField(max_length=300, verbose_name='Notas')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userapp',
            name='university',
        ),
        migrations.RemoveField(
            model_name='userapp',
            name='user_type',
        ),
        migrations.AddField(
            model_name='userapp',
            name='discord_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Discord id'),
        ),
        migrations.CreateModel(
            name='PlayerRaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('party_number', models.PositiveIntegerField(default=None, null=True, verbose_name='Party')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Player', verbose_name='player')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='db.Raid', verbose_name='Raid')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.PlayerClass', verbose_name='Clase'),
        ),
    ]
