# Generated by Django 3.0 on 2022-06-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20220525_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=10, verbose_name='Respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=10, verbose_name='Turno')),
                ('semester', models.CharField(max_length=10, verbose_name='Semestre')),
                ('group', models.CharField(max_length=10, verbose_name='Grupo')),
                ('student_num', models.IntegerField(verbose_name='Número de alumnos')),
                ('init_num', models.IntegerField(verbose_name='Folio inicial')),
                ('end_num', models.IntegerField(verbose_name='Folio final')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='Clave')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('population', models.PositiveIntegerField(verbose_name='Poblacion')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='Clave')),
                ('question', models.CharField(max_length=100, verbose_name='Pregunta')),
                ('option_a', models.CharField(blank=True, max_length=100, null=True, verbose_name='Opción A')),
                ('option_b', models.CharField(blank=True, max_length=100, null=True, verbose_name='Opción B')),
                ('option_c', models.CharField(blank=True, max_length=100, null=True, verbose_name='Opción C')),
                ('option_d', models.CharField(blank=True, max_length=100, null=True, verbose_name='Opción D')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, verbose_name='Nombre del Plantel')),
                ('emstype', models.IntegerField(choices=[(0, 'Secundaria'), (1, 'Media Superior'), (2, 'Superior')], verbose_name='Tipo de subsistema')),
                ('muni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Municipality', verbose_name='Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abrev', models.CharField(max_length=10, verbose_name='Abreviacion')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Subsistema')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=30, verbose_name='Encuesta')),
                ('number_1', models.CharField(max_length=10, verbose_name='Folio1')),
                ('number_2', models.CharField(max_length=10, verbose_name='Folio2')),
                ('type', models.IntegerField(choices=[(0, 'Alumnos'), (1, 'Docentes'), (2, 'No Docentes')], verbose_name='Tipo')),
            ],
        ),
        migrations.RemoveField(
            model_name='playerraid',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerraid',
            name='raid',
        ),
        migrations.RemoveField(
            model_name='userapp',
            name='discord_id',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerClass',
        ),
        migrations.DeleteModel(
            name='PlayerRaid',
        ),
        migrations.DeleteModel(
            name='Raid',
        ),
        migrations.AddField(
            model_name='school',
            name='subsystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Subsystem', verbose_name='Subsistema'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Survey', verbose_name='Encuesta'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.State', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='group',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.School', verbose_name='Plantel'),
        ),
        migrations.AddField(
            model_name='answer',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Group', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Question', verbose_name='Encuesta'),
        ),
    ]
