# Generated by Django 3.0 on 2022-06-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20220622_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.School', verbose_name='Plantel'),
        ),
    ]
