# Generated by Django 3.0 on 2022-06-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_userapp_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Opción E'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='type',
            field=models.IntegerField(choices=[(0, 'Alumnos'), (1, 'Docentes - No Docentes')], verbose_name='Tipo'),
        ),
    ]
