# Generated by Django 3.0 on 2022-06-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20220628_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_e',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Opción E'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Opción D'),
        ),
    ]
