# Generated by Django 3.0 on 2022-06-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20220628_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='frequency',
            field=models.IntegerField(default=0, verbose_name='Frequencia'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='number_1',
            field=models.CharField(max_length=10, verbose_name='Folio inicial'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='number_2',
            field=models.CharField(max_length=10, verbose_name='Folio final'),
        ),
    ]
