# Generated by Django 3.0 on 2022-07-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20220628_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_key',
            field=models.CharField(max_length=50, null=True, verbose_name='Clave del Plantel'),
        ),
    ]
