# Generated by Django 3.0 on 2022-07-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_school_school_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.CharField(max_length=80, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_key',
            field=models.CharField(max_length=50, verbose_name='Clave del Plantel'),
        ),
    ]
