# Generated by Django 3.0 on 2022-07-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20220701_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=250, verbose_name='Pregunta'),
        ),
    ]
