# Generated by Django 3.0 on 2022-07-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20220704_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.School', verbose_name='Plantel'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Group', verbose_name='Grupo'),
        ),
    ]
