# Generated by Django 3.0 on 2022-07-04 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20220704_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.School', verbose_name='Plantel'),
        ),
    ]
