# Generated by Django 3.0 on 2022-07-20 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20220704_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='subsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Subsystem', verbose_name='Subsistema'),
        ),
        migrations.AlterField(
            model_name='school',
            name='subsystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='db.Subsystem', verbose_name='Subsistema'),
        ),
    ]
