# Generated by Django 3.0 on 2022-07-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20220720_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='student_num',
            field=models.IntegerField(default=0, verbose_name='Número de alumnos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='teacher_num',
            field=models.IntegerField(default=0, verbose_name='Número de docentes'),
            preserve_default=False,
        ),
    ]
