# Generated by Django 3.0 on 2022-07-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20220723_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='level',
            field=models.IntegerField(blank=True, choices=[(0, 'Secundaria'), (1, 'Media Superior'), (2, 'Superior'), (3, 'Municipio'), (4, 'Estado')], null=True, verbose_name='Nivel'),
        ),
    ]
