# Generated by Django 3.0 on 2022-08-01 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_userapp_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='db.School', verbose_name='Plantel'),
        ),
    ]
