# Generated by Django 3.0 on 2022-08-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20220801_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Municipality', verbose_name='Municipio'),
        ),
    ]
