# Generated by Django 3.0 on 2022-08-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_userapp_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(default='', max_length=250, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='school',
            name='reprobation',
            field=models.IntegerField(default=0, verbose_name='Reprobacion'),
        ),
        migrations.AddField(
            model_name='school',
            name='terminal_efficiency',
            field=models.IntegerField(default=0, verbose_name='Eficiencia terminal'),
        ),
    ]
