# Generated by Django 3.0 on 2022-08-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_auto_20220807_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='reprobation',
            field=models.FloatField(default=0, verbose_name='Reprobacion'),
        ),
        migrations.AlterField(
            model_name='school',
            name='terminal_efficiency',
            field=models.FloatField(default=0, verbose_name='Eficiencia terminal'),
        ),
    ]
