# Generated by Django 3.0 on 2025-12-23 13:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_auto_20220807_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_teacher', models.BooleanField(blank=True, null=True, verbose_name='Estudiante/Maestro(pdf)')),
                ('is_teacher', models.BooleanField(blank=True, null=True, verbose_name='Es Maestro')),
                ('is_school', models.BooleanField(blank=True, null=True, verbose_name='Es Escuela')),
                ('is_subsystem', models.BooleanField(blank=True, null=True, verbose_name='Es subsistema')),
                ('is_system', models.BooleanField(blank=True, null=True, verbose_name='Es sistema')),
                ('is_muni', models.BooleanField(blank=True, null=True, verbose_name='Es municipio')),
                ('system', models.IntegerField(blank=True, null=True, verbose_name='Sistema (0,1,2)')),
                ('system_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del sistema')),
                ('simple', models.BooleanField(blank=True, null=True, verbose_name='Simple')),
                ('level', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nivel')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Resultado en json')),
                ('muni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Municipality', verbose_name='Municipio')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.School', verbose_name='Plantel')),
                ('subsystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Subsystem', verbose_name='Subsistema')),
            ],
        ),
    ]
